# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'QrCodeBinarySample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for QrCodeBinarySample
  pod 'ZXingObjC', '~> 3.2.1'

  target 'QrCodeBinarySampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'QrCodeBinarySampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
